name: Test, Build and Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - name: Install
        run: yarn
      - name: Test
        run: yarn test:inversiland
      - name: Build
        run: yarn build:inversiland
      - name: Publish
        working-directory: packages/inversiland
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
